# Generated by Django 4.1.7 on 2023-04-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('we', 'Wedding'), ('bi', 'Birthday'), ('gr', 'Graduation'), ('br', 'Bridal Shower'), ('ba', 'Baby Shower')], default='we', max_length=2),
        ),
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('C', 'Catering'), ('E', 'Entertainment'), ('D', 'Decor'), ('T', 'Transportation')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='poc',
            field=models.CharField(default='none', max_length=12),
            preserve_default=False,
        ),
    ]
