# Generated by Django 4.1.7 on 2023-04-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.CharField(default='fakeemailaddress@fake.com', max_length=254),
            preserve_default=False,
        ),
    ]
