# Generated by Django 4.1.7 on 2023-04-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_vendor_cost_vendor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
