# Generated by Django 4.1.7 on 2023-04-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_event_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='vendors',
        ),
        migrations.AddField(
            model_name='vendor',
            name='events',
            field=models.ManyToManyField(blank=True, to='main_app.event'),
        ),
    ]
