# Generated by Django 4.2 on 2023-04-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cat',
            new_name='vendor',
        ),
    ]
