# Generated by Django 4.1.7 on 2023-04-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_event_vendors_vendor_events'),
        ('main_app', '0008_rename_cat_photo_vendor'),
    ]

    operations = [
    ]
